classdef ConfigDegrading < robotics.ros.Message
    %ConfigDegrading MATLAB implementation of octomap_pa_msgs/ConfigDegrading
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'octomap_pa_msgs/ConfigDegrading' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1aed10f0a6882d2e879fff4b7a42e5f9' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        DegradingTime
        AutoDegrading
        AutoDegradingIntervall
    end
    
    properties (Constant, Hidden)
        PropertyList = {'AutoDegrading', 'AutoDegradingIntervall', 'DegradingTime'} % List of non-constant message properties
        ROSPropertyList = {'auto_degrading', 'auto_degrading_intervall', 'degrading_time'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ConfigDegrading(msg)
            %ConfigDegrading Construct the message object ConfigDegrading
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function degradingtime = get.DegradingTime(obj)
            %get.DegradingTime Get the value for property DegradingTime
            degradingtime = single(obj.JavaMessage.getDegradingTime);
        end
        
        function set.DegradingTime(obj, degradingtime)
            %set.DegradingTime Set the value for property DegradingTime
            validateattributes(degradingtime, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigDegrading', 'DegradingTime');
            
            obj.JavaMessage.setDegradingTime(degradingtime);
        end
        
        function autodegrading = get.AutoDegrading(obj)
            %get.AutoDegrading Get the value for property AutoDegrading
            autodegrading = logical(obj.JavaMessage.getAutoDegrading);
        end
        
        function set.AutoDegrading(obj, autodegrading)
            %set.AutoDegrading Set the value for property AutoDegrading
            validateattributes(autodegrading, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'ConfigDegrading', 'AutoDegrading');
            
            obj.JavaMessage.setAutoDegrading(autodegrading);
        end
        
        function autodegradingintervall = get.AutoDegradingIntervall(obj)
            %get.AutoDegradingIntervall Get the value for property AutoDegradingIntervall
            autodegradingintervall = single(obj.JavaMessage.getAutoDegradingIntervall);
        end
        
        function set.AutoDegradingIntervall(obj, autodegradingintervall)
            %set.AutoDegradingIntervall Set the value for property AutoDegradingIntervall
            validateattributes(autodegradingintervall, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigDegrading', 'AutoDegradingIntervall');
            
            obj.JavaMessage.setAutoDegradingIntervall(autodegradingintervall);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.DegradingTime = obj.DegradingTime;
            cpObj.AutoDegrading = obj.AutoDegrading;
            cpObj.AutoDegradingIntervall = obj.AutoDegradingIntervall;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.DegradingTime = strObj.DegradingTime;
            obj.AutoDegrading = strObj.AutoDegrading;
            obj.AutoDegradingIntervall = strObj.AutoDegradingIntervall;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.DegradingTime = obj.DegradingTime;
            strObj.AutoDegrading = obj.AutoDegrading;
            strObj.AutoDegradingIntervall = obj.AutoDegradingIntervall;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.octomap_pa_msgs.ConfigDegrading.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.octomap_pa_msgs.ConfigDegrading;
            obj.reload(strObj);
        end
    end
end
