classdef ConfigBase < robotics.ros.Message
    %ConfigBase MATLAB implementation of octomap_pa_msgs/ConfigBase
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'octomap_pa_msgs/ConfigBase' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7c39442b04d86284e497ea5b0ec084aa' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        OutputFrame
        MapResolution
    end
    
    properties (Constant, Hidden)
        PropertyList = {'MapResolution', 'OutputFrame'} % List of non-constant message properties
        ROSPropertyList = {'map_resolution', 'output_frame'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ConfigBase(msg)
            %ConfigBase Construct the message object ConfigBase
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function outputframe = get.OutputFrame(obj)
            %get.OutputFrame Get the value for property OutputFrame
            outputframe = char(obj.JavaMessage.getOutputFrame);
        end
        
        function set.OutputFrame(obj, outputframe)
            %set.OutputFrame Set the value for property OutputFrame
            outputframe = convertStringsToChars(outputframe);
            
            validateattributes(outputframe, {'char', 'string'}, {}, 'ConfigBase', 'OutputFrame');
            
            obj.JavaMessage.setOutputFrame(outputframe);
        end
        
        function mapresolution = get.MapResolution(obj)
            %get.MapResolution Get the value for property MapResolution
            mapresolution = single(obj.JavaMessage.getMapResolution);
        end
        
        function set.MapResolution(obj, mapresolution)
            %set.MapResolution Set the value for property MapResolution
            validateattributes(mapresolution, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigBase', 'MapResolution');
            
            obj.JavaMessage.setMapResolution(mapresolution);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.OutputFrame = obj.OutputFrame;
            cpObj.MapResolution = obj.MapResolution;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.OutputFrame = strObj.OutputFrame;
            obj.MapResolution = strObj.MapResolution;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.OutputFrame = obj.OutputFrame;
            strObj.MapResolution = obj.MapResolution;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.octomap_pa_msgs.ConfigBase.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.octomap_pa_msgs.ConfigBase;
            obj.reload(strObj);
        end
    end
end
